### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by pptx704** [luisnquin/nao#5]
So apparently now looks for the /tmp/ directory which doesn't exist on windows. Maybe selecting paths based on os version would be better.

**Comment by luisnquin** [comment]
Originally, the project did not target anything other than Linux or Darwin, which caused me to never test it there. Sure i can fix it

Thanks for reporting this bug

**Comment by luisnquin** [comment]
Which terminal editor are you using @pptx704?

**Comment by pptx704** [comment]
@luisnquin I am using Vim. It was shipped with git-scm.

**Comment by luisnquin** [comment]
I've a weird error when trying to use it with `git-scm`, it's related to the final actions of the program when exited, thing that should block the affected notes but not when using it with at least `powershell`, I'll merge and close this MR with my current compatibility fixes

@imlucyd please help me by creating a new issue about that
